awx_version: 10.0.0

awx_web_hostnames:
  wwp: awx-wwp.epfl.ch
  wwp-test: awx-poc-vpsi.epfl.ch

awx_runner_base_image_name: ansible-runner
awx_runner_base_image_fullname: docker.io/ansible/ansible-runner:latest
awx_runner_image_name: "wp-ansible-runner"

awx_wpveritas_inventory: "{{ awx_wpveritas_inventories[ansible_oc_namespace] }}"
awx_wpveritas_inventories:
  wwp: prod
  wwp-test: test
