awx_version: 10.0.0

awx_web_hostnames:
  wwp: awx-wwp.epfl.ch
  wwp-test: awx-poc-vpsi.epfl.ch

awx_runner_base_image_name: ansible-runner
awx_runner_base_image_fullname: docker.io/ansible/ansible-runner:latest
awx_runner_image_name: "wp-ansible-runner"

awx_task_base_image_fullname: "docker.io/ansible/awx_task:{{ awx_version }}"
awx_task_image_name: "wp-awx-task"

awx_web_base_image_name: "awx_web"
awx_web_base_image_fullname: "docker.io/ansible/awx_web:{{ awx_version }}"
awx_web_image_name: "wp-awx-web"

awx_inventory: "{{ awx_inventories[ansible_oc_namespace] }}"
awx_inventories:
  wwp: prod
  wwp-test: test

awx_service_account: awx
# wp-awx-runner must be privileged for now in order to run as an UID
# of our choice, until such time that we reorganize NFS permissions:
awx_runner_service_account: useroot
