---
# tasks file for minishift-dns-check

- name: "Minishift Precondition Checks"
  import_tasks: checks.yml
  tags:
    - never
    - check

- name: "Minishift Database Secrets"
  import_tasks: db-secrets.yml

- name: "persistent volume"
  import_tasks: mnsft-persistent-volume.yml