backup_restic_repo_base: >-
  s3:{{ s3_backup.endpoint_url }}/{{ s3_backup.bucket_name }}/backup/wordpresses/{{ inventory_hostname }}
# restic's tagging system is just bananas. Segregate the two backup streams entirely
backup_restic_repo_files: "{{ backup_restic_repo_base }}/files"
backup_restic_repo_sql:   "{{ backup_restic_repo_base }}/sql"

backup_restic_environment:
  AWS_ACCESS_KEY_ID:     '{{ lookup("env_secrets", "restic_backup_credentials", "AWS_ACCESS_KEY_ID") }}'
  AWS_SECRET_ACCESS_KEY: '{{ lookup("env_secrets", "restic_backup_credentials", "AWS_SECRET_ACCESS_KEY") }}'
  RESTIC_PASSWORD:       '{{ lookup("env_secrets", "restic_backup_credentials", "RESTIC_PASSWORD") }}'
