# file: roles/wordpress-instance/vars/main.yml
#
# Define variables that are used throughout this role.
#
# See ../defaults/main/*.yml for the variables the user is expected to
# provide (either through the inventory file, so-called "group_vars",
# or on the command line)
#
# See also the other files in this directory for variables that are
# only used by some of the tasks in this role. While this file,
# roles/wordpress-instance/vars/main.yml is implicitly imported
# whenever the "wordpress" role is in play in a playbook, the other
# files in this directory need to be imported explicitly using the
# include_vars task.

# The top-level directory of this WordPress instance
wp_dir: "/srv/{{ wp_env }}/{{ wp_hostname }}/htdocs/{{ wp_path }}"

# The .htaccess commanding over this WordPress instance
wp_htaccess_path: "{{ wp_dir }}/.htaccess"

# The path to the wp-config.php file
wp_path_config_php: "{{ wp_dir }}/wp-config.php"

# The path to the wp-admin directory - we stat(2) this to determine
# whether a given site is "symlinked"
wp_path_wpadmin: "{{ wp_dir }}/wp-admin"

# The prefix to invoke the WP-CLI for this WordPress instance
wp_cli_command: "wp --path={{ wp_dir }}"

# The public-facing URL of this instance
wp_base_url: "https://{{ wp_hostname }}/{{ wp_path }}"

wp_themes_dir:  "{{ wp_dir }}/wp-content/themes"
wp_plugins_dir: "{{ wp_dir }}/wp-content/plugins"

# Shortcuts to facts collected by ../tasks/facts.yml
wp_is_installed: "{{ ansible_facts.ansible_local.wp_is_installed }}"
wp_is_symlinked: "{{ ansible_facts.ansible_local.wp_is_symlinked }}"
wp_plugin_list: "{{ ansible_facts.ansible_local.wp_plugin_list }}"

# Range of IPv4 addresses that we could be making RPCs from (in
# particular, to Tequila)
wp_ops_rpcclient_ipv4_range: 10.180.21.0/24

wp_use_gutenberg: '{{ wp_ensure_symlink_version is defined and (wp_ensure_symlink_version | float) >= 5.0 }}'

wpveritas_api_url: '{{ _wpveritas_servers[openshift_namespace] }}'
_wpveritas_servers:
  wwp: https://wp-veritas.epfl.ch/api
  wwp-test: https://wp-veritas.128.178.222.83.nip.io/api
