# Things Ansible should know about symlinks to PHP code on NFS
#
# Please have all variable names start with `symlinks` or `_symlinks`.

symlinks_paths_wp:
  - wp-admin
  - wp-cron.php
  - wp-includes
  - wp-load.php
  - wp-login.php
  - wp-settings.php
  # These index.php files are meant to prevent information disclosure
  # (when folks idly edit out the end their URL bar, and Apache
  # obligingly serves them a directory index)
  - wp-content/plugins/index.php
  - wp-content/themes/index.php
  - wp-content/mu-plugins/index.php

