# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
sudo: required

env:
  global:
    - GITHUB_API_USER=domq
    # This is the GitHub API token, encrypted (so that it can be
    # safely stored on GitHub) with a public key whose corresponding
    # private key is owned by Travis. To regenerate it:
    #
    # 1. Create a token as per
    #    https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
    #    You don't need or want to grant any additional permissions
    #    (checkboxes in the Web UI) to this token
    # 2. `cd` to the wp-ops Git work tree, type `travis login` and
    #    authenticate using your GitHub credentials
    # 3. Type
    #
    #       travis encrypt GITHUB_API_TOKEN=aaaaabbbbbbcccccc
    #
    #    replacing `aaaaabbbbbbcccccc` with the token you obtained at step 1
    - secure: "PZd/0E0sbNpyb1LCfreRpq1z/ojG+8IiW5RL7A4pn1Bk6/ZRFFXCs6tk047CyADFCtlwWSOAKI/BOB/eHmBuyIgBV7ImWNJl6pR6NjRwjbuV94r3OTRslIXzU/sCP8CAbtSiUDwMIqKah7sdEFHDfHNsGqJd/jlFrPNhD7rjwNSY4NQUMxZXAbX6GMghzNVDK2bqw4xpqiyQ2P3Ch0BR77O2pyQBUYSbd1doQz3GEAO7ap5lls3lrMWB8bdDBMJjnoYsWkYMEPNyLCpk60rNLFkCr/4W6uv76EugYAjfiMTsPmjgSV9dANeg2A9647haMK412+vY6HsQw6UntfIYSEF3Vb3olaofIXOUiFgI/Fdjw1KQ1Objb/Sh63PuDwJ5Ipirlm5ryIt/fuuJ6oKBBethhs7LNJcxiOHz3qEgbrfegtgc7MGFQ5QZ2u61BFHPSglgBBTTrBpl7HyifkVbZ3c2faycfzgz7FzIBDQ+3tCRx8BhGzMbETxCbv8c7z3nfR3M6k7ymnS2HVllKGNQOTiF7W8iK3eZ81Lyx4ZPOl+MqDiC50dy5aT1x+xLnyVek7j49LuOenucRuOEWeKhNM8qmJ34qC2GsuVRMB5TWPUFXNA3jckZwj7ZrypBZjoQorw1n9rtcJ23+qeqJmJp50QcoqvHMB/9chdAmAj9caA="

services:
- docker

script:
# Build wp-base first (because other images depend on it)
- |
  set -e -x
  docker pull ubuntu:bionic

  wp_base_branch_build_arg=
  other_dockers_build_args=
  if [ -n "$TRAVIS_BRANCH" ]; then
    wp_base_branch_build_arg="--manifest-url=https://raw.githubusercontent.com/epfl-idevelop/wp-ops/$TRAVIS_BRANCH/ansible/roles/wordpress-instance/tasks/plugins.yml"
    other_dockers_build_args="--build-arg WP_OPS_BRANCH=$TRAVIS_BRANCH"
  fi
  docker build \
     --build-arg "GITHUB_API_USER=${GITHUB_API_USER}"           \
     --build-arg "GITHUB_API_TOKEN=${GITHUB_API_TOKEN}"         \
     --build-arg "INSTALL_AUTO_FLAGS=--exclude=wp-media-folder $wp_base_branch_build_arg" \
     -t epflidevelop/os-wp-base docker/wp-base
  find docker -mindepth 1 -maxdepth 1 -type d \
    | grep -v wp-base | xargs -t -n 1 docker build $other_dockers_build_args
