# Ansible playbook for the EPFL WordPress stack

- name: Initial checks
  hosts: all
  gather_facts: no    # Ansible facts are useless for this play
  tasks:
    - name: Check Ansible version
      run_once: true
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: |
          You must update Ansible to at least 2.6 to use this playbook.

- name: WordPress instances
  hosts: all
  gather_facts: no    # Ansible facts are useless for this play
  tasks:
    # Do a conditional include_role, guarded by all the tags that the
    # role uses. That way, when the operator sets a tag on the command
    # line that is not in use in the role (e.g. `-t awx`), we save I *
    # N units of useless work where I ≈ 900 is the number of WordPress
    # instances, and N ≈ 100 is the number of tasks per instance.
    - name: WordPress instances
      include_role:
        name: ../roles/wordpress-instance
      tags: >-
        {{ ( (playbook_dir | dirname) + "/roles/wordpress-instance" ) | find_all_tags }}

# Likewise, members of all-openshift-namespaces are OpenShift
# namespaces, not hosts
- name: OpenShift namespaces
  hosts: all_openshift_namespaces
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/wordpress-openshift-namespace

- name: Ansible Tower (AWX) instances
  hosts: awx_instances
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/awx-instance
