# Set up job templates available to AWX.

- name: "Set up templates job"
  tags: awx.job_template
  awx_script:
    supports_check_mode: yes
    script: |
      {{ lookup("template", "job-templates-create.py") }}

      kwarg = dict(
          job_name = "Set up Themes",
          job_description = "Apply the chosen theme to a WP site",
          job_tags = "themes",
          job_type = "run",
          job_schedule_name = "Set up the theme on WP sites every thursday",
          job_rrule = "DTSTART:20220305T120829Z RRULE:FREQ=WEEKLY;BYDAY=TH",
      )

      update_json_status(changed=get_or_create_job_template(**kwarg))
