# Kubernetes (OpenShift) objects required to run AWX

- include_vars: k8s-vars.yml
- include_vars: "secrets-{{ ansible_oc_namespace }}.yml"

- name: Ansible Tower Rabbit MQ service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: awx-rmq-mgmt
      namespace: "{{ ansible_oc_namespace }}"
      labels:
        app: awx
        name: awx-rmq-mgmt
    spec:
      ports:
        - name: rmqmgmt
          port: 15672
          protocol: TCP
          targetPort: 15672
      selector:
        name: awx-web-deploy

- name: Ansible Tower HTTP service
  openshift:
    state: latest
    apiVersion: v1
    kind: Service
    metadata:
      name: awx-web-svc
      namespace: "{{ ansible_oc_namespace }}"
      labels:
        app: awx
        name: awx-web-svc
    spec:
      externalTrafficPolicy: Cluster
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8052
      selector:
        name: awx-web-deploy
      sessionAffinity: None
      type: NodePort

- name: Ansible Tower ConfigMap
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: awx-config
      namespace: "{{ ansible_oc_namespace }}"
    data:
      awx_settings: "{{ lookup('template', 'awx-settings.py') }}"
      nginx_conf: "{{ lookup('template', 'nginx.conf') }}"
  notify: Restart AWX container

- name: RabbitMQ ConfigMap
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: awx-rabbitmq-config
      namespace: "{{ ansible_oc_namespace }}"
    data:
      enabled_plugins: "[rabbitmq_management,rabbitmq_peer_discovery_k8s]."
      rabbitmq.conf: "{{ lookup('template', 'rabbitmq/conf.j2') }}"
      rabbitmq_definitions.json: |
        {# the empty line under this comment is a necessity (otherwise Ansible will parse the JSON as JSON) #}

        {{ lookup('template', 'rabbitmq/rabbitmq_definitions.json.j2') }}
  notify: Restart AWX container

- name: Ansible Tower secret (awx-secrets)
  openshift:
    state: latest
    apiVersion: v1
    kind: Secret
    metadata:
      name: awx-secrets
      namespace: "{{ ansible_oc_namespace }}"
    type: Opaque
    data:
      admin_password: "{{ awx_admin_password | eyaml(eyaml_keys)  | b64encode }}"
      credentials_py: "{{ lookup('template', 'credentials.py.j2') | b64encode }}"
      environment_sh: "{{ lookup('template', 'environment.sh.j2') | b64encode }}"
      django_secret_key: "{{ django_secret_key | eyaml(eyaml_keys) | b64encode }}"
      pg_password: "{{ awx_postgresql_database['password'] | eyaml(eyaml_keys)  | b64encode }}"
      rabbitmq_erlang_cookie: "{{ awx_erlang_cookie | eyaml(eyaml_keys) | b64encode }}"
      rabbitmq_password: "{{ awx_rabbitmq_password | eyaml(eyaml_keys) | b64encode }}"
  notify: Restart AWX container

- name: awx service account
  openshift:
    state: latest
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: awx
      namespace: "{{ ansible_oc_namespace }}"

# For awx-rabbitmq containers to discover each other using rabbit_peer_discovery_k8s,
# it is necessary to run the pods as part of a StatefulSet; see
# https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s
- name: Ansible Tower StatefulSet
  openshift:
    state: latest
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: awx
      namespace: "{{ ansible_oc_namespace }}"
    spec:
      selector:
        matchLabels:
          app: awx
          name: awx-web-deploy
          service: django
      serviceName: awx
      template:
        metadata:
          labels:
            app: awx
            name: awx-web-deploy
            service: django
        spec:
          containers:
          #####################################################
          - name: awx-web
            image: "ansible/awx_web:{{ awx_version }}"
            ports:
            - containerPort: 8052
              protocol: TCP
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
            volumeMounts:
            - name: awx-application-config
              mountPath: /etc/tower
              readOnly: true
            - name: awx-application-credentials
              mountPath: /etc/tower/conf.d/
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            env:
              - name: WPVERITAS_INVENTORIES
                value: "{{ awx_wpveritas_inventory }}"
          #####################################################
          - name: awx-celery
            command:
            - /usr/bin/launch_awx_task.sh
            image: "ansible/awx_task:{{ awx_version }}"
            resources:
              requests:
                cpu: 250m
                memory: 2Gi
            volumeMounts:
            - name: awx-application-config
              mountPath: /etc/tower
              readOnly: true
            - name: awx-application-credentials
              mountPath: /etc/tower/conf.d/
              readOnly: true
          #####################################################
          - name: awx-rabbit
            env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_NODENAME
              value: rabbit@$(MY_POD_IP)
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_erlang_cookie
                  name: awx-secrets
            - name: K8S_SERVICE_NAME
              value: awx-rmq-mgmt
            image: "ansible/awx_rabbitmq:{{ awx_rabbitmq_version }}"
            livenessProbe:
              exec:
                command:
                - rabbitmqctl
                - status
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            ports:
            - containerPort: 15672
              name: http
              protocol: TCP
            - containerPort: 5672
              name: amqp
              protocol: TCP
            readinessProbe:
              exec:
                command:
                - rabbitmqctl
                - status
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            resources:
              requests:
                cpu: 250m
                memory: 2Gi
            volumeMounts:
            - name: awx-rabbitmq-config
              mountPath: /etc/rabbitmq
          #####################################################
          - name: awx-memcached
            image: memcached:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
          #####################################################


          dnsPolicy: ClusterFirst
          restartPolicy: Always
          serviceAccount: awx
          serviceAccountName: awx
          terminationGracePeriodSeconds: 10
          volumes:
          - name: awx-application-config
            configMap:
              name: awx-config
              defaultMode: 420
              items:
              - key: awx_settings
                path: settings.py
          - name: awx-application-credentials
            secret:
              defaultMode: 420
              items:
              - key: credentials_py
                path: credentials.py
              - key: environment_sh
                path: environment.sh
              - key: django_secret_key
                path: django_secret_key
              secretName: awx-secrets
          - name: awx-rabbitmq-config
            configMap:
              name: awx-rabbitmq-config
              defaultMode: 420
              items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
              - key: enabled_plugins
                path: enabled_plugins
              - key: rabbitmq_definitions.json
                path: rabbitmq_definitions.json
          - name: nginx-config
            configMap:
              name: awx-config
              items:
                - key: nginx_conf
                  path: nginx.conf

- meta: flush_handlers

- name: Ansible Tower route for the Web front-end
  openshift:
    state: latest
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: awx-web-svc
      namespace: "{{ ansible_oc_namespace }}"
    spec:
      host: "{{ awx_web_hostnames[ansible_oc_namespace] }}"
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: awx-web-svc
