- name: "Ansible Tower OpenShift objects"
  import_tasks: k8s.yml
  tags:
    - awx.k8s
    - awx.openshift

- name: "Ansible Tower database operations"
  include_tasks: ops.yml
  # These tags are *not* auto-applied down, since we use an
  # include_tasks rather than an import_tasks or include directive.
  # This means that every task in awx-ops.yml must have its own
  # specific set of tags.
  tags:
    - never
    - awx.dump
    - awx.restore

- name: "Set up `{{ awx_project_name }}` project"
  awx_script:
    supports_check_mode: yes
    script: |
      {{ lookup("template", "awx_script_lib.py") }}

      from awx.main.models.organization import Organization
      from awx.main.models.projects import Project
      with AnsibleGetOrCreate(Organization, name="{{ awx_organization_name }}") as org:
          with AnsibleGetOrCreate(Project, name="{{ awx_project_name }}") as prj:
            prj.organization = org
            prj.scm_type = "git"
            prj.scm_url = "{{ awx_project_github_url }}"
            prj.scm_branch = "{{ git_current_branch }}"

- import_tasks: container-group.yml

- import_tasks: inventories.yml
