# Daemonset for profiling metrics run on all nodes

- name: Telegraf Daemonset
  openshift:
    state: latest
    apiVersion: apps/v1    
    kind: DaemonSet
    metadata:
      name: telegraf
      namespace: "{{ ansible_oc_namespace }}"
    
    spec:
      selector:
        matchLabels:
          name: telegraf

      template:
        spec:
          containers:
            - name: telegraf
              image: telegraf:1.15-alpine
        metadata:
          labels:
            name: telegraf


