# Custom runner image with the `wp` command-line tool and a WordPress layout in /wp
- include_vars: ../../../vars/image-vars.yml
- include_vars: k8s-vars.yml

- name: "Pull {{ awx_runner_base_image_name }} from Docker Hub"
  openshift:
    state: latest
    apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: "{{ awx_runner_base_image_name }}"
      namespace: "{{ ansible_oc_namespace }}"
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: '{{ awx_runner_base_image_fullname }}'
          importPolicy:
            scheduled: true

- name: "{{ awx_runner_image_name }} ImageStream"
  openshift:
    state: latest
    apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: "{{ awx_runner_image_name }}"
      namespace: "{{ ansible_oc_namespace }}"
    # No spec — We build it from a BuildConfig, below


- name: "{{ awx_runner_image_name }} image build automation"
  openshift:
    state: latest
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: "{{ awx_runner_image_name }}"
      namespace:  "{{ ansible_oc_namespace }}"
    spec:
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
      source:
        type: Dockerfile
        dockerfile: |
          FROM {{ awx_runner_wp_mixin_image_fullname }}
          FROM {{ awx_runner_base_image_fullname }}

          RUN yum -y install php-cli

          COPY --from=0 /usr/local/bin/wp /usr/local/bin/
          RUN mkdir /runner/.wp-cli
          COPY --from=0 /var/www/.wp-cli /runner/.wp-cli
      output:
        to:
          kind: "ImageStreamTag"
          name: "{{ awx_runner_image_name_and_tag }}"
      triggers:
        - type: "ImageChange"
          imageChange:
            from:
              kind: "ImageStreamTag"
              name: "{{ awx_runner_wp_mixin_image_name_and_tag }}"
              namespace: "{{ awx_mgmt_build_namespace }}"
        - type: "ImageChange"
          imageChange:
            from:
              kind: "ImageStreamTag"
              name: "{{ awx_runner_base_image_name_and_tag }}"
              namespace: "{{ awx_mgmt_build_namespace }}"
  register: _awx_runner_buildconfig

- name: "Rebuild {{ awx_runner_image_name }} now"
  when: _awx_runner_buildconfig is changed
  shell: "oc -n {{ awx_mgmt_build_namespace }} start-build {{ awx_runner_image_name }}"
