# Set a sane configuration for this WordPress instance

- include_vars: wp-destructive.yml

- assert:
    that:
      - wp_can.configure or ansible_check_mode

- name: Detect whether a WordPress database update is needed
  shell: '{{ wp_cli_command }} core update-db --dry-run'
  changed_when: false
  register: _wp_core_db_update_dry_run

- name: Do WordPress database update
  shell:
    cmd: |
      {{ wp_cli_command }} core update-db
  when: >
    "already" not in _wp_core_db_update_dry_run.stdout

- name: Check whether ping_sites is set
  command: "{{ wp_cli_command }} option get ping_sites"
  changed_when: false
  register: _wp_config_ping_sites

- name: Unset ping_sites
  command: "{{ wp_cli_command }} option set ping_sites ''"
  when: >
    _wp_config_ping_sites is not skipped
    and (_wp_config_ping_sites.stdout != '')
