# Create a WordPress site out of thin air

- name: Create site directory
  file:
    path: "{{ wp_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: no

- name: Run new-wp-site script
  shell:
    chdir: "{{ wp_dir }}"
    cmd: |
      if wp --path="{{ wp_dir }}" eval '1;'; then echo SITE_ALREADY_EXISTS; exit 0; fi

      . /etc/profile.d/k8s-env.sh
      new-wp-site
  register: _new_wp_site
  changed_when: >-
    "SITE_ALREADY_EXISTS" not in _new_wp_site.stdout
