# Create a WordPress site out of thin air

- include_vars: wp-destructive.yml

- assert:
    that:
      - (wp_can.wipe) or (_wp_config_php_stat is not defined) or (not _wp_config_php_stat) or (not _wp_config_php_stat.stat) or (not _wp_config_php_stat.stat.exists)

- name: Create site directory
  file:
    path: "{{ wp_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: no

- name: Run new-wp-site script
  shell:
    chdir: "{{ wp_dir }}"
    cmd: . /etc/profile.d/k8s-env.sh && new-wp-site
