---


- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{name}}"
      name: "{{name}}"
      namespace: "{{ minishift_namespace }}"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: "{{name}}"
        spec:
          serviceAccount: wwp-int
          serviceAccountName: wwp-int
          containers:
#            - env:
#              - name: WP_ENV
#                value: env
            - name: "{{name}}"
              env:
                - name: DB_NAME
                  value: "{{name}}"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: database-access
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: database-access
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: database-access

              image: "wordpress:latest"
              ports:
                - containerPort: 80
                  protocol: TCP
              volumeMounts:
                - mountPath: /var/www/html
                  name: "nfsvol-{{name}}"
                  subPath: "wp/{{name}}"
          volumes:
            - name: "nfsvol-{{name}}"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-mgmt'
      triggers:
        - type: ConfigChange

#        - type: ImageChange
#          imageChangeParams:
#            containerNames:
#            - "{{ name }}"
#            from:
#              kind: ImageStreamTag
#              name: "httpd:prod"
#              namespace: "myproject"
             
  tags: dc
