## Plugin and mu-plugin lineup and configuration
##
## ⚠ Until such time that we don't use the jahia2wp repository, the
## configuration herein duplicates the one at
## https://github.com/epfl-si/jahia2wp/blob/release2018/data/plugins/generic/config-lot1.yml
## (and ditto in the "release" branch as well).
## Please be sure to propagate your changes there as well.

- include_vars: wp-destructive.yml   # For wp_can
- assert:
    that: wp_can.configure or ansible_check_mode

- include_vars: "{{ item }}"
  tags: always
  with_items:
    - plugin-vars.yml
    - "{{ 'plugin-secrets-' + openshift_namespace + '.yml' }}"
    - accred-vars.yml

##################### Plugins to clean ###########################

- name: Delete plugins bundled with WordPress
  wordpress_plugin:
    name: "{{ item }}"
    state: absent
  with_items:
    - akismet
    - hello

- name: Enumerate active plugins
  shell:
    chdir: "{{ wp_dir }}"
    cmd: "wp plugin list --status=active --field=name"
  register: _active_plugins
  changed_when: false
  check_mode: no
  tags: always

- name: Was “coming soon” plug-in active?
  check_mode: no   # That means yes
  shell:
    chdir: "{{ wp_dir }}"
    cmd: wp plugin list --name=coming-soon --status=active --format=count
  changed_when: false
  tags: wp.plugins.coming-soon
  register: _coming_soon_plugin_was_active

- name: Enable Coming Soon on new sites
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_coming_soon_options }}"
  vars:
    plugin_coming_soon_shall_be_enabled: true
  when: >-
    _active_plugins.stdout == ""
  tags: wp.plugins.coming-soon

# We changed the standard operating procedure around mid-2020
# regarding Coming Soon's configuration management. Turning it off
# through its configuration (as opposed to uninstalling the plug-in,
# as we did before) empowers the user and lets them turn Coming Soon
# mode back on at will. The following task is intended to migrate
# WordPress sites to the new way of doing things, without turning
# Coming Soon back on inadvertently (in case the old config was still
# lingering in the wp_options table despite the plug-in having been
# uninstalled). Once this task has run on the entire fleet, it ought
# to be removed.
- name: Disable Coming Soon on sites where the plug-in was previously inactive
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_coming_soon_options }}"
  vars:
    plugin_coming_soon_shall_be_enabled: false
  when: >-
    _active_plugins.stdout != "" and _coming_soon_plugin_was_active.stdout == "0"
  tags: wp.plugins.coming-soon

- name: Coming Soon plugin (always installed)
  wordpress_plugin:
    name: coming-soon
    state:
      - symlinked
      - active
    from: wordpress.org/plugins
  tags: wp.plugins.coming-soon

##################### Must-use plugins ###########################

- name: Custom editor menu (must-use plugin)
  wordpress_plugin:
    name: EPFL_custom_editor_menu_loader
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from:
      - https://github.com/epfl-si/wp-mu-plugins/blob/master/epfl-custom-editor-menu
      - https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_custom_editor_menu_loader.php

- name: Blocks white-list (must-use plugin)
  wordpress_plugin:
    name: EPFL_block_white_list
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_block_white_list.php

- name: Disable comments (must-use plugin)
  wordpress_plugin:
    name: EPFL_disable_comments
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_disable_comments.php

- name: Enable automatic updates (must-use plugin)
  wordpress_plugin:
    name: EPFL_enable_updates_automatic
    is_mu: yes
    state: '{{ "absent" if wp_is_managed else "symlinked" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_enable_updates_automatic.php

- name: Disable automatic updates (must-use plugin)
  wordpress_plugin:
    name: EPFL_disable_updates_automatic
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_disable_updates_automatic.php

- name: Google Analytics hook (must-use plugin)
  wordpress_plugin:
    name: EPFL_google_analytics_hook
    is_mu: yes
    state:
      - symlinked
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_google_analytics_hook.php

- name: Locked installs (must-use plugin)
  wordpress_plugin:
    name: EPFL_installs_locked
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_installs_locked.php

- name: Jahia redirect tracker (must-use plugin)
  wordpress_plugin:
    name: EPFL_jahia_redirect
    is_mu: yes
    state: '{{ "symlinked" if wp_is_managed else "absent" }}'
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_jahia_redirect.php

- name: EPFL functions (must-use plugin)
  wordpress_plugin:
    name: epfl-functions
    is_mu: yes
    state:
      - symlinked
    from: https://github.com/epfl-si/wp-mu-plugins/blob/master/epfl-functions.php

- name: Quota (must-use plugin)
  wordpress_plugin:
    name: EPFL_quota_loader
    is_mu: yes
    state:
      - symlinked
    from:
      - https://github.com/epfl-si/wp-mu-plugins/tree/master/epfl-quota
      - https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_quota_loader.php

- name: Stats (must-use plugin)
  wordpress_plugin:
    name: EPFL_stats_loader
    is_mu: yes
    state:
      - symlinked
    from:
      - https://github.com/epfl-si/wp-mu-plugins/tree/master/epfl-stats
      - https://github.com/epfl-si/wp-mu-plugins/blob/master/EPFL_stats_loader.php

##################### "2018" plugins ###########################

- name: '"TinyMCE Advanced" plugin'
  wordpress_plugin:
    name: tinymce-advanced
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: Gutenberg PDF Viewer Block
  wordpress_plugin:
    name: pdf-viewer-block
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: Gutenberg PDF Flipbook
  wordpress_plugin:
    name: flowpaper-lite-pdf-flipbook
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

# TODO: recapture intent of jahia2wp's
# src/wordpress/plugins/custom/polylang.py
# (perhaps not in this file)

- name: Polylang plugin
  wordpress_plugin:
    name: polylang
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: Count Polylang languages
  shell: |
    {{ wp_cli_command }} pll lang list --field=term_id --format=csv
  changed_when: false
  register: _polylang_languages_csv
  tags: plugins.polylang
  check_mode: no

- name: Polylang translations (taglines, date formats etc)
  wordpress_polylang_language:
    state: present
    language: "{{ item }}"
  with_items: "{{ lookup('wpveritas', 'languages') | languages_in_order }}"
  tags: plugins.polylang
  # We don't want to resurrect languages that the user deleted:
  when: |-
    _polylang_languages_csv.stdout == ""

- name: mainwp-child plugin
  wordpress_plugin:
    name: mainwp-child
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: mainwp_child_uniqueId option
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_mainwp_child_options }}"

- name: Tequila plugin
  wordpress_plugin:
    name: tequila
    state:
      - symlinked
      - active
    from: https://github.com/epfl-sti/wordpress.plugin.tequila/archive/vpsi.zip

- name: Replace WP login screen with redirect-to-Tequila flow
  wordpress_option:
    name: plugin:epfl_tequila:has_dual_auth
    value: 0

- name: Whitelist of IPs for Tequila fetchAttributes request
  wordpress_option:
    name: plugin:epfl:tequila_allowed_request_hosts
    value: "{{ wp_ops_rpcclient_ipv4_range }}"

- name: Accred plugin
  wordpress_plugin:
    name: accred
    state:
      - symlinked
      - active
    from: https://github.com/epfl-sti/wordpress.plugin.accred/archive/vpsi.zip

- name: Accred options
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_accred_options }}"

- name: Cache-Control plugin
  wordpress_plugin:
    name: epfl-cache-control
    state:
      - symlinked
      - active
    from: https://github.com/epfl-si/jahia2wp/tree/release2018/data/wp/wp-content/plugins/epfl-cache-control

- name: Cache-Control options
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_cache_control_options }}"

- name: varnish-http-purge plugin
  wordpress_plugin:
    name: varnish-http-purge
    state: absent

- name: EPFL-settings plugin
  wordpress_plugin:
    name: EPFL-settings
    state:
      - symlinked
      - active
    from: https://github.com/epfl-si/wp-plugin-epfl-settings

- name: EPFL-Content-Filter plugin
  wordpress_plugin:
    name: EPFL-Content-Filter
    state: '{{ ["symlinked", "active"] if plugins_locked else "absent" }}'
    from: https://github.com/epfl-si/wp-plugin-epfl-content-filter

# TODO: we are not quite sure anymore whether this plugin is useful.
- name: SVG-support plugin
  wordpress_plugin:
    name: svg-support
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: remote-content-shortcode plugin
  wordpress_plugin:
    name: epfl-remote-content-shortcode
    state:
      - symlinked
      - active
    from: https://github.com/epfl-si/jahia2wp/tree/release2018/data/wp/wp-content/plugins/epfl-remote-content-shortcode

- name: shortcode-ui plugin
  wordpress_plugin:
    name: shortcode-ui
    state: >-
        {{ "absent" if plugins_use_gutenberg else [ "symlinked", "active" ] }}
    from: wordpress.org/plugins

- name: shortcode-ui-richtext plugin
  wordpress_plugin:
    name: shortcode-ui-richtext
    state: >-
        {{ "absent" if plugins_use_gutenberg else [ "symlinked", "active" ] }}
    from: wordpress.org/plugins

- name: EPFL plugin
  wordpress_plugin:
    name: epfl
    state: >-
      {{ "absent" if plugins_use_gutenberg else [ "symlinked", "active" ]  }}
    from: https://github.com/epfl-si/jahia2wp/tree/release2018/data/wp/wp-content/plugins/epfl

- name: EPFL Gutenberg plugin
  wordpress_plugin:
    name: wp-gutenberg-epfl
    state:
      - symlinked
      - >-
        {{ "active" if plugins_use_gutenberg else "inactive" }}
    from: https://github.com/epfl-si/wp-gutenberg-epfl

- name: EPFL Menus plugin
  wordpress_plugin:
    name: epfl-menus
    state: >-
        {{ "absent" if plugins_use_wp2010_plugins else [ "symlinked", "active" ] }}
    from: https://github.com/epfl-si/wp-plugin-epfl-menus

- name: wp-media-folder plugin
  wordpress_plugin:
    name: wp-media-folder
    state: >-
      {{ "absent" if plugins_use_wp2010_plugins else [ "symlinked", "active" ] }}
    from: https://wp-manager.epfl.ch/resources/plugin-zip/wp-media-folder.zip

- name: wp-media-folder options
  tags: plugins.wp_media_folder_options
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_wpmf_options }}"

- name: very-simple-meta-description plugin
  wordpress_plugin:
    name: very-simple-meta-description
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: epfl-404 plugin
  wordpress_plugin:
    name: epfl-404
    state:
      - symlinked
      - active
    from: https://github.com/epfl-si/wp-plugin-epfl-404

- name: ewww-image-optimizer plugin
  wordpress_plugin:
    name: ewww-image-optimizer
    state:
      - symlinked
      - active
    from: wordpress.org/plugins

- name: ewww-image-optimizer configuration
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_ewww_image_optimizer_options }}"

- name: enlighter plugin
  wordpress_plugin:
    name: enlighter
    state:
      - symlinked
      - active
    from: https://github.com/epfl-si/wp-plugin-enlighter

- name: enlighter configuration
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_enlighter_options }}"

##################### 2010-only plugins ###########################

# These plugins only exist in obsolescent DeploymentConfig's ("unm-*"
# and "subdomains"). Holding off using Ansible on these is an
# acceptable medium-term workaround measure.

- name: feedzy-rss-feeds plugin
  wordpress_plugin:
    name: feedzy-rss-feeds
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: wordpress.org/plugins

- name: simple-sitemap plugin
  wordpress_plugin:
    name: simple-sitemap
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: wordpress.org/plugins

- name: EPFL-Share plugin
  wordpress_plugin:
    name: EPFL-Share
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/EPFL-Share

- name: Shortcodes Ultimate plugin
  wordpress_plugin:
    name: shortcodes-ultimate
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: wordpress.org/plugins

- name: epfl-scheduler plugin
  wordpress_plugin:
    name: epfl-scheduler
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-scheduler

- name: epfl-news plugin
  wordpress_plugin:
    name: epfl-news
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-news

- name: epfl-memento plugin
  wordpress_plugin:
    name: epfl-memento
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-memento

- name: epfl-faq plugin
  wordpress_plugin:
    name: epfl-faq
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-faq

- name: epfl-map plugin
  wordpress_plugin:
    name: epfl-map
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-map

- name: epfl-buttons plugin
  wordpress_plugin:
    name: epfl-buttons
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-buttons

- name: epfl-snippet plugin
  wordpress_plugin:
    name: epfl-snippet
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-snippet

- name: epfl-toggle plugin
  wordpress_plugin:
    name: epfl-toggle
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-toggle

- name: epfl-grid plugin
  wordpress_plugin:
    name: epfl-grid
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-grid

- name: epfl-infoscience plugin
  wordpress_plugin:
    name: epfl-infoscience
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-infoscience

- name: epfl-infoscience-search plugin
  wordpress_plugin:
    name: epfl-infoscience-search
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-infoscience-search

- name: epfl-xml plugin
  wordpress_plugin:
    name: epfl-xml
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-xml

- name: epfl-people plugin
  wordpress_plugin:
    name: epfl-people
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-people

- name: epfl-twitter plugin
  wordpress_plugin:
    name: epfl-twitter
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-twitter

- name: epfl-video plugin
  wordpress_plugin:
    name: epfl-video
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-video

- name: epfl-tableau plugin
  wordpress_plugin:
    name: epfl-tableau
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-tableau

- name: epfl-google-forms plugin
  wordpress_plugin:
    name: epfl-google-forms
    state: "{{ plugins_symlinked_and_active_in_2010_only }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release/data/wp/wp-content/plugins/epfl-google-forms

##################### Category-specific plugins ###########################

- name: epfl-intranet plugin
  wordpress_plugin:
    name: epfl-intranet
    state: "{{ plugins_for_inside_category }}"
    from: https://github.com/epfl-si/wp-plugin-epfl-intranet
  tags:
    - plugins.intranet

- name: epfl-intranet status
  wordpress_plugin_epfl_intranet:
    protection_enabled: '{{ "yes" if "Inside" in wp_site_categories else "no" }}'
    restrict_to_groups: ''
  tags:
    - plugins.intranet

- name: epfl-intranet htaccess
  blockinfile:
    path: "{{ wp_htaccess_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR EPFL-Intranet"
    block: |
      RewriteCond %{REQUEST_URI} wp-content/uploads/
      RewriteRule wp-content/uploads/(.*)$ wp-content/plugins/epfl-intranet/inc/protect-medias.php?file=$1 [QSA,L]
    state: '{{ "present" if "Inside" in wp_site_categories else "absent" }}'
  tags:
    - plugins.intranet
    - plugins.intranet.htaccess

- name: epfl-emploi plugin
  wordpress_plugin:
    name: epfl-emploi
    state: "{{ plugins_for_emploi_category }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release2018/data/wp/wp-content/plugins/epfl-emploi

- name: epfl-restauration plugin
  wordpress_plugin:
    name: epfl-restauration
    state: "{{ plugins_for_restauration_category }}"
    from: https://github.com/epfl-si/wp-plugin-epfl-restauration

- name: EPFL-Library-Plugins plugin
  wordpress_plugin:
    name: EPFL-Library-Plugins
    state: "{{ plugins_for_library_category }}"
    from: https://github.com/epfl-si/wp-plugin-epfl-library

- name: epfl-courses-se plugin
  wordpress_plugin:
    name: epfl-courses-se
    state: "{{ plugins_for_cdhshs_category }}"
    from: https://github.com/epfl-si/jahia2wp/tree/release2018/data/wp/wp-content/plugins/epfl-courses-se

- name: MainWP plugin
  wordpress_plugin:
    name: mainwp
    state: "{{ plugins_for_admin_category }}"
    from: wordpress.org/plugins

- name: WPForms plugin
  wordpress_plugin:
    name: wpforms
    state: "{{ plugins_for_wpforms_category }}"
    from: https://wp-manager.epfl.ch/resources/plugin-zip/wpforms.zip
  tags:
    - wp.plugins.wpforms

- name: WPForms options
  wordpress_option: "{{ item }}"
  with_items: "{{ plugin_wpforms_options }}"
  tags:
    - wp.plugins.wpforms

- name: WPForms-EPFL-Payonline plugin
  wordpress_plugin:
    name: wpforms-epfl-payonline
    state: "{{ plugins_for_payonline_category }}"
    from: https://github.com/epfl-si/wpforms-epfl-payonline/releases/latest/download/wpforms-epfl-payonline.zip
    # Specific release: https://github.com/epfl-si/wpforms-epfl-payonline/releases/download/v1.0.2/wpforms-epfl-payonline.zip
  tags:
    - wp.plugins.wpforms
    - wp.plugins.payonline

- name: Uninstall all unknown plug-ins
  tags: plugins.unknown
  wordpress_unknown_plugins:
    state: absent
    known_plugins_in: "{{ role_path }}/tasks/plugins.yml"  # i.e. this here file
