# Build report from sites and write it to local disk
- name: Create report in /tmp/sites-titles.csv
  copy:
    content: "name,base_url,title,tagline,languages"
    dest: /tmp/sites-titles.csv
  delegate_to: localhost
  check_mode: no
  run_once: true

- name: Get Wordpress options from site
  command: "{{ wp_cli_command }} {{ item.command_name }}"
  with_items:
    - { command_name: option get blogname }
    - { command_name: option get blogdescription }
    - { command_name: pll lang list --field=name --format=csv }
  register: fetched_options
  changed_when: false
  check_mode: no

- name: Append collected data to /tmp/sites-titles.csv
  lineinfile:
    dest: /tmp/sites-titles.csv
    insertafter: EOF
    line: >
      {{inventory_hostname}},{{ wp_base_url}},{{ fetched_options.results[0].stdout }},{{ fetched_options.results[1].stdout }},"{{ fetched_options.results[2].stdout_lines | join(', ') }}"
  delegate_to: localhost
  check_mode: no
