---

- name: id
  shell:
    cmd: id

- meta: end_play

- name: get routes
  connection: local
  shell:
    cmd: |
      set -e -x
      podname=$(oc get pods -o name |grep mgmt | cut -d "/" -f2)
      oc get route  {{domain}} -o yaml
  register: route

- set_fact:
    route_name: "{{route.stdout | from_yaml | uri_filter}}"

- debug:
    var: route_name

- name: run mgmt
  connection: local
  shell:
    cmd: |
      set -e -x
      podname=$(oc get pods -o name |grep mgmt | cut -d "/" -f2)
      oc exec -it $podname -- "/bin/bash" -c 'ls /backups'
#      oc exec -it $podname -- "/bin/bash" -c 'mkdir -p /srv/wp/{{domain}}/{{route_name}}'
  register: out

- set_fact:
   bkp_name: "{{out.stdout | latest_bkp }}"

- debug:
    var: bkp_name