---

- name: id
  shell:
    cmd: id
  register: id
- debug:
    var: id.stdout

- name: directories
  file:  
    path: "{{wp_dir}}"
    owner: www-data
    state: directory

- name: wp evaluation
  shell:
    cmd: |
      echo $({{wp_cli_command }} eval '1;')
  register: out


- debug:
    var: out.stderr

#- name: unzip backup archive
#  shell:
#    cmd: |
#      cd {{wp_dir}}
#      tar xf /backups/{{wp_backup_folder}}/{{wp_archive_name}}
#  when: "'This does not seem to be a WordPress install.' in out.stderr"

- meta: end_play