- name: Get sample page id
  command: "{{ wp_cli_command }} post list --post_type=page --name='sample-page' --format=ids"
  register: _sample_page_id
  changed_when: false

- name: Delete sample page
  command: "{{ wp_cli_command }} post delete 2 --force"
  when:
    - |
      not _sample_page_id.skipped
    - |
      _sample_page_id.stdout == "2"
  register: _page_delete
  changed_when: >-
    "stdout" in _page_delete and "Success" in _page_delete.stdout

- name: Get sample post id
  command: "{{ wp_cli_command }} post list --name='hello-world' --format=ids"
  register: _sample_post_id
  changed_when: false

- name: Delete sample post
  command: "{{ wp_cli_command }} post delete 1 --force"
  when:
    - |
      not _sample_post_id.skipped
    - |
      _sample_post_id.stdout == "1"
  register: _post_delete
  changed_when: >-
    "stdout" in _post_delete and "Success" in _post_delete.stdout

- name: Get Privacy Policy page id
  command: "{{ wp_cli_command }} post list --post_type=page --name='privacy-policy' --format=ids"
  register: _privacy_policy_page_id
  changed_when: false

- name: Delete Privacy Policy page
  command: "{{ wp_cli_command }} post delete 3 --force"
  when:
    - |
      not _privacy_policy_page_id.skipped
    - |
      _privacy_policy_page_id.stdout == "3"
  register: _privacy_policy_page_delete
  changed_when: >-
    "stdout" in _privacy_policy_page_delete and "Success" in _privacy_policy_page_delete.stdout
