# Serving from symlinks: WordPress directories on NFS (aka have your cake),
# but with all PHP code symlinked from /wp (aka eat it too).
#
# This is an *optional* set of tasks that only run when either `-t
# symlink` or `-t unsymlink` is specified. Note that these tags are
# *not* auto-propagated by caller; therefore, each task must
# explicitly specify under which circumstances (= set of tags) it is
# to run.
#
# Also note that some of the symlink-related tasks are performed
# unconditionnally by configure.yml, which invokes this file. This
# file is for operations that *require* downtime / operator awareness,
# such as symlinking a previously unsymlinked site or vice versa.
#
# Being (or not being) a symlinked site also has consequences w.r.t.
# templated configuration files; see configure.yml for details.

- assert:
    that:
      - (wp_can.configure and wp_can.write_code) or ansible_check_mode

- include_vars: symlink-vars.yml
  tags: always

- name: "Set wp_is_symlinked"
  tags: always
  set_fact:
    wp_is_symlinked: '{{ "symlink" in ansible_run_tags }}'

# WP_CONTENT_DIR can be set in wp-config.php prior to symlinking
# without ill effects:
- name: "Reconfigure wp-config.php, index.php and the “main” symlink first"
  tags: symlink
  include_tasks:
    file: serving-infrastructure.yml
    apply:
      tags: ["symlink"]

- name: "Symlink pieces of the WordPress core"
  tags: symlink
  check_mode: no
  shell:
    cmd: |
      {{ lookup("template", "symlinks-lib.sh") }}
      {{ lookup("template", "maintenance-lib.sh") }}

      set -e -x
      cd {{ wp_dir }}

      if make_symlinks_to_wp --check {{ symlinks_managed_in_bulk | join(" ") }}; then exit; else :; fi

      {% if not ansible_check_mode %}
      enter_maintenance_mode
      trap leave_maintenance_mode EXIT HUP INT QUIT

      if make_symlinks_to_wp {{ symlinks_managed_in_bulk | join(" ") }}; then :; else
          case "$?" in
              1) echo "SYMLINKS_CHANGED" ;;
              *) exit $?                 ;;
          esac
      fi

      {% endif %}
  register: _symlink_script
  changed_when: >
    "SYMLINKS_CHANGED" in _symlink_script.stdout

- name: "Unsymlink (copy from /wp)"
  tags: unsymlink
  check_mode: no
  shell:
    cmd: |
      {{ lookup("template", "symlinks-lib.sh") }}
      {{ lookup("template", "maintenance-lib.sh") }}

      set -e -x
      cd {{ wp_dir }}

      if ensure_file_contains index.php <<INDEX_PHP
      {{ lookup('template', 'wordpress-index.php') }}
      INDEX_PHP
      then
          :
      else
          case "$?" in
              1) echo INDEX_PHP_CHANGED ;;
              *) exit $?                ;;
          esac
      fi

      {% if not ansible_check_mode %}
      enter_maintenance_mode
      trap leave_maintenance_mode EXIT HUP INT QUIT
      {% endif %}

      if [ "" = "$(find . -name uploads -prune -false -o -type l)" ]; then
        echo NO_SYMLINKS
        exit 0
      fi

      {% if ansible_check_mode %}
      exit 0
      {% endif %}

      for subdir in wp-content/themes wp-content/plugins \
                    wp-content/mu-plugins; do
        if ! [ -L "$subdir" ]; then
          find "$subdir" -type l -delete
        fi
      done
      find . wp-content -maxdepth 1 -type l -delete

      (cd /wp; tar clf - .) | tar xpvf -
  register: _unsymlink_script
  changed_when: >
    "INDEX_PHP_CHANGED" in _unsymlink_script.stdout or
    "NO_SYMLINKS" not in _unsymlink_script.stdout

- name: "Verify that there are no stale files on symlinked site"
  tags: symlink
  check_mode: no
  shell:
    cmd: |
      # Trim all files at top level (except for a whitelist), and
      # the auto-update muplugin

      set -e -x
      cd "{{ wp_dir }}"

      for path in * \
          wp-content/mu-plugins/EPFL_enable_updates_automatic.php
      do
          case "$path" in
              .ht*) continue ;;
              *.ini) continue ;;
              wp|wp-config.php|index.php) continue ;;
              ansible-backup-*) continue ;;
              {{ symlinks_managed_in_bulk | join('|') }}) continue ;;
          esac
          if [ ! -e "$path" ]; then continue; fi
          {# We can't remove “flying” directories, as they might contain
             sub-sites: #}
          if [ -d "$path" ]; then continue; fi

          echo FILES_TO_TRIM=$path
      done
  register: _symlink_cleanup_script
  changed_when: '"FILES_TO_TRIM" in _symlink_cleanup_script.stdout'

- name: "Reconfigure wp-config.php after unsymlinking"
  tags: unsymlink
  include_tasks:
    file: serving-infrastructure.yml
    apply:
      tags: ["unsymlink"]



