ci_jenkins_public_hostname: jenkins-wwp-test.epfl.ch
ci_jenkins_persistent_volume_name: wordpress-test-volume-jenkins
ci_jenkins_persistent_volume_claim_name: wordpress-jenkins

ci_name_stem: httpd-jenkins
ci_prod_or_dev : "{{ 'prod' if openshift_namespace == 'wwp' else 'dev' }}"
ci_buildconfig_name: "{{ ci_name_stem }}-{{ ci_prod_or_dev }}"

ci_jenkins_master_image_name: jenkins-openshift-epfl
ci_jenkins_master_git_build:
  repository: 'https://github.com/epfl-idevelop/wp-ops'
  ref: wwp-continuous-integration
  path: docker/jenkins

ci_jenkins_test_sidekick_image_name: cucumberjs
ci_jenkins_test_sidekick_git_build:
  repository: 'https://github.com/epfl-idevelop/wp-dev'
  path: docker/acceptance

ci_jenkins_slave_image_name: "jenkins-agent"
ci_jenkins_slave_docker_image: quay.io/openshift/origin-jenkins-agent-base

ci_jenkins_openshift_console_base_url: https://pub-os-exopge.epfl.ch/console
ci_jenkins_test_target: https://migration-wp.epfl.ch/www.epfl.ch/
