ci_jenkins_public_hostname: jenkins-wwp-test.epfl.ch
ci_jenkins_persistent_volume_name: wordpress-test-volume-jenkins
ci_jenkins_persistent_volume_claim_name: wordpress-jenkins

ci_name_stem: httpd-jenkins
ci_prod_or_dev : "{{ 'prod' if openshift_namespace == 'wwp' else 'dev' }}"
ci_buildconfig_name: "{{ ci_name_stem }}-{{ ci_prod_or_dev }}"

ci_jenkins_master_image_name: jenkins-openshift-epfl
ci_jenkins_master_image_stream_tag: "{{ ci_jenkins_master_image_name }}:latest"

ci_jenkins_slave_imagestream_name: "jenkins-agent"
ci_jenkins_slave_docker_image: quay.io/openshift/origin-jenkins-agent-base
