httpd_image_name: httpd
mgmt_image_name: mgmt
wp_base_image_name: wp-base
varnish_image_name: varnish

wp_ops_git_uri: https://github.com/epfl-idevelop/wp-ops
# wp_ops_git_branch is defined in
# ../../../hosts-{dev,prod}/group_vars/openshift-namespaces-{dev,prod}
