monitoring_prober_image_name: monitoring-menus-probe

_prometheus_secrets: "{{ lookup('file', '/keybase/team/epfl_wp_prod/ansible_prometheus_secrets.yml') | from_yaml }}"
prometheus_htpass: "\n{% for cred in _prometheus_secrets.prometheus.credentials %}\n          - \"{{ cred.user }}:{{ cred.pass | password_hash('bcrypt') }}\"\n{% endfor %}"
