# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp-test.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

webhooks:
  github:
    sorryserver: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAfOZC3Lx8xhXXvdkty7fav5nzjwp6cUiags/nW1wRzqb2JuB7uPGWETFaw4O7xGFA+VXnBWPZzfRMdWviibAhNEqNsIU7lbzQBcICqIwG2mqbCk/SigY4X74t582avNFOUhngZ3l1XRwXlZNz1TbKaulLk7SNG2qVHaI+LHJeRrg2gTmz6nDQ5a/bAYMYt2WlxmQpVeGIqRRTE/3F/i7Lq2u0e+Dp2SVI2yRbNzge+CwbZO+63xLKOo0y47ijgsQrVPjQWjtoz6gNhj9rth4jJV58VcXhEkRtVKCAfs1Nd7a85IclRrp16hRxovmt9+LkzVoM4/eo8YeAIFQjuBHxuDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDHx0hzK0jnlGtSUASh3ZTjgBAKAldyI0xceu4WHgkp9XK/]
