# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-openshift-namespace/vars/secrets-wwp-test.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

mysql_super_credentials:
  host: db-wwp.epfl.ch
  user: oswproot
  password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEATvqqylC7kf78EVi0unKPRcASCIOV+77qcdYXl9EEtJT9aNbodrYg+oM/0jJScQ3TlPmoqFCLJHUA7FOnmAmonIwqNJ5SUYAOFRN1eftuxLSeg0Tn2CqH/9x3dCig8AZ+4DP1/5KBIVljTpbMZd4MaQr7lKZulpzl5EdCHnSmrro6fqnwr8ebnxOxFCxH6vwDt68czvfuxonE+21sN5UwwMDQ590vp7PmyowWgBnVd5xAaP+uI26NtpxsSMYRXE+gp4blD4Ntd/nMtCwBvWXqv5UHTlux+8NxWeFgtFHj8Q61O6FOoTPb6072bV3Y091m4QKBzvf8ZzHSkg60KitV6zBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCk+PxidO78uJVrgfkZGj08gCB7RBfIbQby1sTGfPppxO2Fa0mB1w7549aOxYJaf2l4uw==]

github_api_token:
  user: domq
  token: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAIF9kReHIcVqqeLy6mF6EN+Q+Q4uGwyn1P6nNPiR3arc/RbNqhSuqv7gh5g1vR6NQCTWIYhZCjpWXSs0e4EBB9WchD6AwEzYlj98MpR3ZxN045LZ62YDtE3MZeXZPjrvbVsFxY3PeEdYe9JUV6Qpm4jxMM21tBwlf9ag39GWktvjEMgF0heO1TMuGUZZmZwqMLPY+f3UwRZKHEF3pUIAzUVEZKAskNz2/Oc8mNgmCj9+RDt4diMY7cgpeV7oIBa3rUw4omK9fBjimfsFKaUU+D0XQc5JN3s3TBQ47fcjtMY0VRyVR/2Q8n7cxpRmiH9d4uN0l2tEVL4q7uiYcwafgijBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCVcACcZlLYead3w6zY4iTCgDAnzq0ra/FFDKZLf/yFD2AvRdkE1FbY+VvIOt08kdRpJQa+v1CDyN/sLR9yO4/ucaA=]
