# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_prod.pem \
#     ansible/roles/wordpress-openshift-namespace/vars/secrets-prometheus-wwp.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

prometheus:
  credentials:
    -
      user: c2c_federate
      pass: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEApX5yZ5vtIXLGcidH5WwNDkFfxyFSgTNO8MXXuvN2c0md/Cd4W9qt7kYDt1JxLW4BN+5g1FNn0t/0fIDLafYQX4ubc+i9+HfuT98WGAKHxEuiR41nHUTm8uJWHEM7J11ruCY/+DNnYfnaj/9jmrRSSPgsJiCu3mECzEanv3g6yMe8EuZ3Vbj/L+eLBOpEWOJN7SvB807Ec+1laGjYuBuPimwAVsdFcXI0Shbq//L5OLgE52NrAYERoZvHDTdis2VqyF5A88w4Didx479wLoM2k3yka+jaAm7z5/qQbUI+mh4X7poAINCeFThH8w7OySAIoLCbGaBhz6aBsSxdWCdF9TBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBC9KifajowxbgyU0flyiVcqgCDm22TqomPGOHJLddnkIGsjtbxMxXJounX3wXdBwPsO3w==]
    -
      user: vpsiwp
      pass: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAJHmiNDF2WNuGVwfGW6PslS0fBic+vDJC2p63XPHvrLiEITgJD94rsePmfV3GUh113tiTPvmCEyPzeoR0/WaJHIhG5nb2BxSFdo2sBXYwyA/0P/yqxZJrE4wtgcLGWdF3Kk+mT0Q7h1An2ZnNmz94YhP3RtIJwqIccUUcqVA5hNr3LyKJbHFQK3JaXdbovgqRPTCQWonbt8ugEsz3bwSUTk4o4UQ0L4KeyOQU8B5YwxNAZZLDh1g/SJn9VhdExF1gUStkFQqxHmgrrLi4VPZSg80VhxL9XOvD7ixtqkzAIyMinzfLC2qRTZdxuZPW2/jJ4h4QPADL7TIDC0AARawarzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDaeokujhheceQ9A4mrBVNngBAovS9y3rYKJ29+Pt5PYKOA]
    -
      user: admin
      pass: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEARyy4MzUB/2rmOpESvkh6fY0QIi8UsOx7MoJ9Fq6OhEnEyc/cDI0e9zJ8S+ubbP5eSfBi4iqZY6QYL0IX4K/pToyOnNrb5sG8VBlKQ2PYSCXu+ssfRW9O0uJVuDkDUwYVa9RK0yY2CWurEhxrXodHBthVUTiZQIp+1BxZaftKALysTR5HOURWC96tFh1BYfMEKju8mhEXgmeq55Dgx9RanNiS7fcCLZ4uSmlqNajb4RagEergPhoBkYxDbZs7bNXkDjXc6mVlVNqyktDAUFmUJGpMlGNn7kxyoiyB1yc+5hxoJEhaUVmYT0w+HiPELqF33FR0l0oLcz91vkxea20ZCjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBb3Hi/I/UNylgaqUZiG/ZugCDzps69dZ93iQ0VUulOoyV7+TAJxsx3egmXy60l/WLUFQ==]
