# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_prod.pem \
#     ansible/vars/secrets-wwp.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

mysql_super_credentials:
  host: db-wwp.epfl.ch
  user: oswproot
  password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAhQrxreyVJ1+FfZXad6k7+B5nwHQmHufkGFwmjmRLRNOlPkFI3AUetZQlZLRdnxJLRCk9/MCDrvwxoM5WponQXWmia8cnDLJWaWCnWiWDR/nXT4Y/zGogS04/uTueCvXhlXDQiJ/BCAy9fRRamT2RHdeuGLoNYnjw/o1hoaJCERLPVTzk3CH3BLzBGiFRLO24PvjdGlN9HzuE+kAP4Rioe+S0RDFfE7vBw1FnzaUgqmlX4LWMw5aDuxp68zvFsof6Je3FIL91s0QLG+d6gFsQ0onQoq/O+N6CtG5x6cHcHvVK68zvkeZm5eBl+BQMwTsE9TkkB6G3eDqkotdgsK5tgDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCIAB2AiqvOSdVDQe+c/pq+gCC5CztzXWK10DHVdaBGiI9cUa5we+HTDRrnQYU+wpClQg==]
