# AWX-compatible playbook for the EPFL WordPress stack
#
# Other operations, that deal with the "superstructure" (e.g.
# OpenShift jobs, secrets) are handled from ../interactive-playbooks/
# since it makes no sense to run them from AWX. (Also, AWX finds
# playbooks only in the `playbooks` subdirectories)

# In this play, "hosts" are not really hosts; rather, they are
# WordPress instances. See the list in
# ../inventory/test/wordpress-instances and
# ../inventory/prod/wordpress-instances (executable scripts, that lists
# them on standard output)
- name: WordPress instances
  hosts: all-wordpresses
  gather_facts: no   # But see ../roles/wordpress-instance/tasks/facts.yml
  roles:
    - role: ../roles/wordpress-instance
