# Ansible playbook for the EPFL WordPress stack

- name: Initial checks
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    - name: Check Ansible version
      run_once: true
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: |
          You must update Ansible to at least 2.6 to use this playbook.

# In this play, "hosts" are not really hosts; rather, they are
# WordPress instances. See the list in
# ../hosts-dev/wordpress-instances (a plain file) and
# ../hosts-prod/prod-wordpresses (an executable script, that lists
# them on standard output)
- name: WordPress instances
  hosts: all-wordpresses
  gather_facts: no   # Delayed again until "setup:" below
  pre_tasks:
    - name: Ansible pre-configuration
      set_fact:
        ansible_user: www-data
        ansible_python_interpreter: "/srv/{{wp_env}}/venv/bin/python"
    - name: Create and use remote temporary directory (if required)
      include_tasks: '{{ "../tasks/remote-tempdir.yml" if play_dump is match("yes") else "../tasks/noop.yml" }}'
    - name: Gathering facts (delayed after Ansible pre-configuration)
      setup:
  roles:
    - role: ../roles/wordpress-instance

# Likewise, members of all-openshift-namespaces are OpenShift
# namespaces, not hosts
- name: OpenShift namespaces
  hosts: all-openshift-namespaces
  gather_facts: no   # Useless here, afaict
  roles:
    - role: ../roles/wordpress-openshift-namespace
