---

- name: "Prepare nfs files"
  connection: local
  shell:
      cmd: |
        PODNAME=$(oc get pods -o name |grep mgmt | cut -d "/" -f2 |head -1)
        oc exec $PODNAME -- mkdir -p /srv/{{env}}


- name: "PersistentVolume"
  connection: local
  openshift:
    as_user: "system:admin"
    state: latest
    kind: PersistentVolume
    name: "nfs-pv-{{env}}"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: 'nfs-pv-{{env}}'
      labels:
          id: "{{env}}"
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: '/srv/{{env}}'
        server: "{{IPADRS}}"
        readOnly: false
  tags: pv
