---
# Infrastructure deployment tasks
#
- name: pv
  import_tasks: "mnsft-mgmt-persistent-volume.yml"
  tags:
    - blue

- name: pvc
  import_tasks: "mnsft-mgmt-persistent-claim.yml"
  tags:
    - blue

- name: OpenProject deployment
  import_tasks: "mnsft-deploy-mgmt.yml"
  tags:
    - blue

- name: OpenProject service
  import_tasks: "mnsft-serve-mgmt.yml"
  tags:
    - blue
- name: OpenProject route
  import_tasks: "mnsft-route-mgmt.yml"
  tags:
    - blue

#