# Kubernetes configuration for production-related images and their builds
#
# Builds happen in the wwp-test namespace *only.* The images are then
# promoted using `oc tag` or an equivalent API call.
#
# See also continuous-integration.yml (which has its own set of images)

- include_vars: image-vars.yml
  tags:
    - always

- name: "Testing ImageStreams and their build information"
  when: not openshift_is_production and not openshift_namespace == "wwp-int"
  openshift_imagestream:
    name: "{{ item.name }}"
    namespace: "{{ openshift_namespace }}"
    metadata: "{{ item.metadata | default({}) }}"
    from: "{{ item.from | default(None) }}"
    git:
        repository: "{{ wp_ops_git_uri }}"
        path: "{{ item.git_path }}"
  with_items:
    - name: "{{ wp_base_image_name }}"
      git_path: docker/wp-base
    - name: "{{ httpd_image_name }}"
      git_path: docker/httpd
      from: "{{ wp_base_image_name }}"
    - name: "{{ mgmt_image_name }}"
      git_path: docker/mgmt
      from: "{{ wp_base_image_name }}"

- name: "Production ImageStreams"
  when: openshift_is_production
  openshift_imagestream:
    name: "{{ item.name }}"
    namespace: "{{ openshift_namespace }}"
    metadata: "{{ item.metadata | default({}) }}"
  with_items:
    - name: "{{ httpd_image_name }}"
    - name: "{{ mgmt_image_name }}"


#TODO figure out an automated way to pull prod images
- name: "wwp-int ImageStreams"
  when: openshift_namespace == "wwp-int"
  openshift_imagestream:
    name: "{{ item.name }}"
    namespace: "{{ openshift_namespace }}"
    metadata: "{{ item.metadata | default({}) }}"
  with_items:
    - name: "{{ httpd_image_name }}"
    - name: "{{ mgmt_image_name }}"

- name: "Minishift mirror ImageStreams"
  when: openshift_namespace == "myproject"
  openshift:
    state: latest
    content: |
      apiVersion: v1
      kind: ImageStream
      namespace: {{ openshift_namespace }}
      metadata:
        name: {{item.name}}
        namespace: {{ openshift_namespace }}
      spec:
        dockerImageRepository: {{epfl_openshift_registry_repo}}/{{item.name}}
  with_items:
    - name: "{{ httpd_image_name }}"
    - name: "{{ mgmt_image_name }}"



# re-imports images on the image stream if it is linked to a docker registry
- name: "Resync images"
  shell:
    cmd: |
      set -e -x
      oc import-image {{item.name}}:prod
  with_items:
    - name: "{{ httpd_image_name }}"
    - name: "{{ mgmt_image_name }}"
  tags:
    - never
    - resync
