---



- name: "PersistentVolume"
  openshift:
    as_user: "system:admin"
    state: latest
    kind: PersistentVolume
    name: "nfs-pv-{{name}}"
    namespace: "{{ openshift_namespace }}"
    apiVersion: v1
    metadata:
      name: 'nfs-pv-{{name}}'
      labels:
          id: "{{name}}"
    spec:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: '/site/{{name}}'
        server: "{{nfs_ip}}"
        readOnly: false
  tags: pv
