---


- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "mgmt"
      name: "mgmt"
      namespace: "{{ minishift_namespace }}"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: "mgmt"
        spec:
          serviceAccount: wwp-int
          serviceAccountName: wwp-int
          containers:
            - name: "mgmt"
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: database-access
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: database-access
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: database-access
              volumeMounts:
                - mountPath: "/{{nfs_path}}"
                  name: "nfsvol-mgmt"
                - mountPath: /backups
                  name: "backups"
          volumes:
            - name: "nfsvol-mgmt"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-mgmt'
            - name: backups
              persistentVolumeClaim:
                claimName: backups-readonly
       
      triggers:
        - type: ConfigChange

        - type: ImageChange
          imageChangeParams:
            containerNames:
            - "mgmt"
            from:
              kind: ImageStreamTag
              name: "mgmt:prod"
              namespace: "{{ minishift_namespace }}"
             
  tags: dc
