---


- name: "dc/{{ dc.name }}"
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{dc.name}}"
      name: "{{dc.name}}"
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
#      selector:
#        run: "{{dc.name}}"
      template:
        when: dc.db_ip is undefined
        metadata:
          labels:
            run: "{{dc.name}}"
        spec:
          containers:
            - image: 'wordpress:latest'
              name: "{{dc.name}}"
              command:
                - /usr/local/bin/apache2-foreground
              volumeMounts:
                - mountPath: /var/www/html
                  name: "nfsvol-{{dc.name}}"
          volumes:
            - name: "nfsvol-{{dc.name}}"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-{{dc.name}}'
      triggers:
        - type: ConfigChange
             
  tags: dc
