---
- name: "PersistentVolumeClaim"
  connection: local
  openshift:
    state: latest
    kind: PersistentVolumeClaim
    name: "nfs-pvc-mgmt"
    namespace: "{{openshift_namespace}}"
    apiVersion: v1
    metadata:
      name: 'nfs-pvc-mgmt'
      annotations:
        volume.beta.kubernetes.io/storage-class: wwp-int-wordpress-sites
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 250Gi

  tags: pvc


- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "mgmt"
      name: "mgmt"
      namespace: "{{ openshift_namespace }}"
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: "mgmt"
        spec:
          serviceAccount: wwp-int
          serviceAccountName: wwp-int
          containers:
            - name: "mgmt"
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: host
                      name: database-access
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: database-access
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: database-access
              volumeMounts:
                - mountPath: /srv
                  name: "nfsvol-mgmt"
                - mountPath: /backups
                  name: "backups"
          volumes:
            - name: "nfsvol-mgmt"
              persistentVolumeClaim:
                claimName: 'nfs-pvc-mgmt'
            - name: backups
              persistentVolumeClaim:
                claimName: backups-readonly
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            containerNames:
            - "mgmt"
            from:
              kind: ImageStreamTag
              name: "mgmt:prod"
              namespace: "{{ openshift_namespace }}"
             
  tags: dc

- name: "Service"
  connection: local
  openshift:
    state: latest
    kind: Service
    name: "mgmt"
    namespace: "{{ openshift_namespace }}"
    apiVersion: v1
    metadata:
        name: "mgmt"
        labels:
          run: "mgmt"
        namespace: "{{openshift_namespace}}"
    spec:
        selector:
            run: "mgmt"
        ports:
        - port: 80
          protocol: TCP
          targetPort: 80
  tags: svc

- name: "Route"
  connection: local
  openshift:
    state: latest
    kind: Route
    name: "mgmt"
    namespace: "{{ openshift_namespace }}"
    apiVersion: v1
    metadata:
        name: "mgmt"
    spec:
        host: "mgmt-{{openshift_namespace}}.128.178.222.83.nip.io"
        port:
            targetPort: 80
        to:
            kind: Service
            name: "mgmt"
  tags: rt

- name: "Deployment rollout"
  connection: local
  shell:
    cmd: oc rollout latest dc/mgmt
  tags: rollout