---

- include_vars: mgmt-vars.yml
  tags: always
- include_vars: ../../../vars/ssh-keys.yml  # Required by mgmt-vars.yml
  tags: always
- include_vars: image-vars.yml              # For mgmt_image_name
  tags: always
- include_vars: ../../../vars/persistent-ressources.yml
  tags: always


- name: "PersistentVolumeClaim"
  connection: local
  openshift:
    state: latest
    kind: PersistentVolumeClaim
    name: "nfs-pvc-mgmt"
    namespace: "{{openshift_namespace}}"
    apiVersion: v1
    metadata:
      name: 'nfs-pvc-mgmt'
      annotations:
        volume.beta.kubernetes.io/storage-class: wwp-int-wordpress-sites
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 250Gi

  tags: pvc

- name: "{{ mgmt_secret_name }} secret (ssh host and user keys)"
  openshift:
    state: latest
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ mgmt_secret_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: mgmt-test
      data:
        {{ mgmt_secret_contents | to_yaml | indent(width=2) }}

- name: DeploymentConfigs
  connection: local
  openshift:
    state: latest
    content: |
      apiVersion: v1
      kind: DeploymentConfig
      metadata:
        name: "mgmt-test"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "mgmt-test"
      spec:
        replicas: 1
        selector:
          app: "mgmt-test"
          deploymentconfig: "mgmt-test"
        template:
          metadata:
            labels:
              app: "mgmt-test"
              deploymentconfig: "mgmt-test"
          spec:   
            containers:
              - name: "mgmt-test"
                imagePullPolicy: Always
                ports:
                - containerPort: 22
                  protocol: TCP
      {% if openshift_is_wp_int %}
                env:
                  - name: DB_HOST
                    valueFrom:
                      secretKeyRef:
                        key: host
                        name: database-access
                  - name: DB_USER
                    valueFrom:
                      secretKeyRef:
                        key: username
                        name: database-access
                  - name: DB_PASS
                    valueFrom:
                      secretKeyRef:
                        key: password
                        name: database-access
      {% endif %}
                volumeMounts:
                  - mountPath: /srv
                    name: "nfsvol-mgmt"
      {% if (openshift_is_production or openshift_is_wp_int) %}
                  - mountPath: /backups
                    name: "backups"
      {% endif %}
                  - name: ssh
                    mountPath: /var/lib/secrets/ssh
            serviceAccount: wwp-int
            serviceAccountName: wwp-int
            volumes:
              - name: "nfsvol-mgmt"
                persistentVolumeClaim:
                  claimName: '{{openshift_pvc_name}}'
              - name: ssh
                secret:
                  secretName: "{{ mgmt_secret_name }}"
      {% if (openshift_is_production or openshift_is_wp_int) %}
              - name: backups
                persistentVolumeClaim:
                  claimName: backups-readonly
      {% endif %}
        triggers:
          - type: ConfigChange
          - type: ImageChange
            imageChangeParams:
              containerNames:
              - "mgmt-test"
              from:
                kind: ImageStreamTag
                name: "mgmt:prod"
                namespace: "{{ openshift_namespace }}"
               
  tags: dc


- name: "Deployment rollout"
  connection: local
  shell:
    cmd: oc rollout latest dc/mgmt-test
  tags: rollout
